name: Deploy to staging

on:
  push:
    branches:
      - staging
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploying to staging
        run: echo "I wish I have a staging environment"

      - name: Download auto 
        run: curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto && chmod a+x ~/auto
      
      - name: Do PreRelease 
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ~/auto next 

      
    



